type User {
  id: ID!
  name: String
  age: Int
}

type Query {
  users: [User]
}

type Mutation {
  createUser(id: ID!, name: String!, age: Int!): User
  updateUser(id: ID!, name: String, age: Int): User
  deleteUser(id: ID!): User
}

schema {
  query: Query
  mutation: Mutation
}
